version: '2.2'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: docker.io/adagioworkflow/adagio
    command:
      - adagiod
      - -backend-type=etcd
      - -etcd-addresses=http://etcd:2379
      - api
    ports:
      - "7890:7890"
    restart: always
  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: docker.io/adagioworkflow/adagio
    command:
      - adagiod
      - -backend-type=etcd
      - -etcd-addresses=http://etcd:2379
      - agent
    restart: always
    scale: 3
  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: docker.io/adagioworkflow/adagio
    command:
      - adagiogw
      - -adagiod-addr=api:7890
    volumes:
      - "./ui/:/ui/"
    ports:
      - "7891:7891"
    depends_on:
      - api
  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    image: docker.io/adagioworkflow/ui
    ports:
      - "8080:8080"
    depends_on:
      - gateway
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.3
    command:
      - /usr/local/bin/etcd
      - -name=etcd1
      - -advertise-client-urls=http://0.0.0.0:2379
      - -initial-advertise-peer-urls=http://0.0.0.0:2380
      - -listen-client-urls=http://0.0.0.0:2379
      - -listen-peer-urls=http://0.0.0.0:2380
      - -initial-cluster=etcd1=http://0.0.0.0:2380
