version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "ON"
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: make test 

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
