version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - setup_remote_docker

      - run: make docker-etcd

      - run: make test-with-integrations

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
