// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/rpc/controlplane/service.proto

package controlplane

import (
	context "context"
	fmt "fmt"
	adagio "github.com/georgemac/adagio/pkg/adagio"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{0}
}

func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

type StatsResponse struct {
	Stats                *adagio.Stats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{1}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetStats() *adagio.Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type StartRequest struct {
	Spec                 *adagio.GraphSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{2}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetSpec() *adagio.GraphSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type StartResponse struct {
	Run                  *adagio.Run `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{3}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

func (m *StartResponse) GetRun() *adagio.Run {
	if m != nil {
		return m.Run
	}
	return nil
}

type InspectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InspectRequest) Reset()         { *m = InspectRequest{} }
func (m *InspectRequest) String() string { return proto.CompactTextString(m) }
func (*InspectRequest) ProtoMessage()    {}
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{4}
}

func (m *InspectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectRequest.Unmarshal(m, b)
}
func (m *InspectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectRequest.Marshal(b, m, deterministic)
}
func (m *InspectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectRequest.Merge(m, src)
}
func (m *InspectRequest) XXX_Size() int {
	return xxx_messageInfo_InspectRequest.Size(m)
}
func (m *InspectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InspectRequest proto.InternalMessageInfo

func (m *InspectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type InspectResponse struct {
	Run                  *adagio.Run `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InspectResponse) Reset()         { *m = InspectResponse{} }
func (m *InspectResponse) String() string { return proto.CompactTextString(m) }
func (*InspectResponse) ProtoMessage()    {}
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{5}
}

func (m *InspectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectResponse.Unmarshal(m, b)
}
func (m *InspectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectResponse.Marshal(b, m, deterministic)
}
func (m *InspectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectResponse.Merge(m, src)
}
func (m *InspectResponse) XXX_Size() int {
	return xxx_messageInfo_InspectResponse.Size(m)
}
func (m *InspectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InspectResponse proto.InternalMessageInfo

func (m *InspectResponse) GetRun() *adagio.Run {
	if m != nil {
		return m.Run
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{6}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListRunsResponse struct {
	Runs                 []*adagio.Run `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListRunsResponse) Reset()         { *m = ListRunsResponse{} }
func (m *ListRunsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRunsResponse) ProtoMessage()    {}
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{7}
}

func (m *ListRunsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRunsResponse.Unmarshal(m, b)
}
func (m *ListRunsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRunsResponse.Marshal(b, m, deterministic)
}
func (m *ListRunsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRunsResponse.Merge(m, src)
}
func (m *ListRunsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRunsResponse.Size(m)
}
func (m *ListRunsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRunsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRunsResponse proto.InternalMessageInfo

func (m *ListRunsResponse) GetRuns() []*adagio.Run {
	if m != nil {
		return m.Runs
	}
	return nil
}

type ListAgentsResponse struct {
	Agents               []*adagio.Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListAgentsResponse) Reset()         { *m = ListAgentsResponse{} }
func (m *ListAgentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAgentsResponse) ProtoMessage()    {}
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44473a7dc25ad712, []int{8}
}

func (m *ListAgentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentsResponse.Unmarshal(m, b)
}
func (m *ListAgentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentsResponse.Marshal(b, m, deterministic)
}
func (m *ListAgentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentsResponse.Merge(m, src)
}
func (m *ListAgentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAgentsResponse.Size(m)
}
func (m *ListAgentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentsResponse proto.InternalMessageInfo

func (m *ListAgentsResponse) GetAgents() []*adagio.Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

func init() {
	proto.RegisterType((*StatsRequest)(nil), "adagio.rpc.controlplane.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "adagio.rpc.controlplane.StatsResponse")
	proto.RegisterType((*StartRequest)(nil), "adagio.rpc.controlplane.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "adagio.rpc.controlplane.StartResponse")
	proto.RegisterType((*InspectRequest)(nil), "adagio.rpc.controlplane.InspectRequest")
	proto.RegisterType((*InspectResponse)(nil), "adagio.rpc.controlplane.InspectResponse")
	proto.RegisterType((*ListRequest)(nil), "adagio.rpc.controlplane.ListRequest")
	proto.RegisterType((*ListRunsResponse)(nil), "adagio.rpc.controlplane.ListRunsResponse")
	proto.RegisterType((*ListAgentsResponse)(nil), "adagio.rpc.controlplane.ListAgentsResponse")
}

func init() { proto.RegisterFile("pkg/rpc/controlplane/service.proto", fileDescriptor_44473a7dc25ad712) }

var fileDescriptor_44473a7dc25ad712 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x95, 0x34, 0x2d, 0xed, 0xe4, 0x4f, 0x9b, 0x01, 0x11, 0x64, 0x81, 0xa8, 0x16, 0x02,
	0xa5, 0x48, 0x76, 0xd5, 0xc2, 0x05, 0xc4, 0x01, 0x38, 0x20, 0x24, 0x0e, 0xc8, 0xbd, 0x71, 0x5b,
	0x9c, 0x95, 0x59, 0x35, 0xec, 0x2e, 0xbb, 0xeb, 0x5e, 0x10, 0x17, 0x5e, 0x81, 0x27, 0xe2, 0x19,
	0x78, 0x05, 0x1e, 0x04, 0xed, 0x1f, 0x3b, 0x2e, 0x6a, 0xdc, 0x9e, 0xa2, 0xdd, 0xf9, 0xbe, 0xf9,
	0xc5, 0xf3, 0x8d, 0x0d, 0x44, 0x9d, 0x95, 0x99, 0x56, 0x45, 0x56, 0x48, 0x61, 0xb5, 0x5c, 0xaa,
	0x25, 0x15, 0x2c, 0x33, 0x4c, 0x9f, 0xf3, 0x82, 0xa5, 0x4a, 0x4b, 0x2b, 0x71, 0x46, 0x17, 0xb4,
	0xe4, 0x32, 0xd5, 0xaa, 0x48, 0xdb, 0xb2, 0x64, 0xe6, 0xcc, 0xa1, 0x18, 0x7f, 0x82, 0x23, 0xb9,
	0x5b, 0x4a, 0x59, 0x2e, 0x59, 0x46, 0x15, 0xcf, 0xa8, 0x10, 0xd2, 0x52, 0xcb, 0xa5, 0x30, 0xa1,
	0x4a, 0x26, 0x30, 0x3a, 0xb5, 0xd4, 0x9a, 0x9c, 0x7d, 0xab, 0x98, 0xb1, 0xe4, 0x19, 0x8c, 0xe3,
	0xd9, 0x28, 0x29, 0x0c, 0xc3, 0x07, 0xb0, 0x69, 0xdc, 0xc5, 0x9d, 0xde, 0x7e, 0xef, 0x60, 0x78,
	0x3c, 0x4e, 0x63, 0xf3, 0xa0, 0x0a, 0x35, 0xf2, 0xdc, 0x77, 0xd1, 0x36, 0x76, 0xc1, 0x39, 0x0c,
	0x8c, 0x62, 0x45, 0xf4, 0x4c, 0x6b, 0xcf, 0x3b, 0x4d, 0xd5, 0x97, 0x53, 0xc5, 0x8a, 0xdc, 0x97,
	0x49, 0xea, 0x61, 0xce, 0x16, 0x61, 0xf7, 0x60, 0x43, 0x57, 0x22, 0xda, 0x86, 0xb5, 0x2d, 0xaf,
	0x44, 0xee, 0xee, 0xc9, 0x3e, 0x4c, 0xde, 0x0b, 0xe7, 0x6c, 0x40, 0x13, 0xe8, 0xf3, 0x85, 0xd7,
	0xef, 0xe4, 0x7d, 0xbe, 0x20, 0x47, 0xb0, 0xdb, 0x28, 0xae, 0xd7, 0x73, 0x0c, 0xc3, 0x0f, 0xdc,
	0xd4, 0x0d, 0xc9, 0x09, 0xec, 0xf9, 0x63, 0x25, 0x56, 0x23, 0xb8, 0x0f, 0x03, 0x5d, 0x09, 0x37,
	0x81, 0x8d, 0xff, 0x5b, 0xf8, 0x02, 0x79, 0x09, 0xe8, 0x4c, 0xaf, 0x4b, 0x26, 0x5a, 0x93, 0x9b,
	0xc3, 0x16, 0xf5, 0x37, 0xd1, 0xd8, 0x8c, 0xce, 0xeb, 0xf2, 0x58, 0x3c, 0xfe, 0x3d, 0x80, 0xd1,
	0xdb, 0x90, 0xe4, 0x47, 0x97, 0x24, 0x72, 0xd8, 0xf4, 0xc3, 0xc5, 0x79, 0xba, 0x26, 0xec, 0xb4,
	0x1d, 0x59, 0xf2, 0xe8, 0x2a, 0x59, 0xf8, 0x3f, 0x64, 0xfa, 0xf3, 0xcf, 0xdf, 0x5f, 0xfd, 0x21,
	0xee, 0x64, 0xe7, 0x47, 0x99, 0xcf, 0x0d, 0xcf, 0x3c, 0x4a, 0xdb, 0x6e, 0x54, 0x93, 0x6b, 0x37,
	0x6a, 0x95, 0x23, 0xb9, 0xe9, 0x51, 0xe3, 0x64, 0xdb, 0xa1, 0xdc, 0x88, 0x5e, 0xf4, 0x0e, 0xf1,
	0x2b, 0x6c, 0xd7, 0xa3, 0xc5, 0x87, 0x6b, 0x1b, 0xb5, 0xc2, 0x48, 0x9e, 0x74, 0xab, 0x5a, 0x19,
	0x91, 0x3d, 0x4f, 0x04, 0x6c, 0x88, 0x58, 0xc1, 0x8d, 0xb8, 0x0a, 0xf8, 0x78, 0x6d, 0x9f, 0x8b,
	0xeb, 0x94, 0x1c, 0x5c, 0x2d, 0x8c, 0xbc, 0x99, 0xe7, 0x4d, 0x71, 0xb7, 0xe6, 0x65, 0xdf, 0xf9,
	0xe2, 0xd5, 0xe1, 0x0f, 0x34, 0x00, 0xab, 0x5d, 0xb8, 0xe6, 0x73, 0x3e, 0xed, 0x54, 0x5d, 0x5c,
	0x2b, 0x82, 0x9e, 0x3c, 0x42, 0x70, 0xe4, 0xb0, 0x43, 0x6f, 0x6e, 0x7f, 0xba, 0x75, 0xd9, 0xb7,
	0xe3, 0xf3, 0x96, 0x7f, 0xc9, 0x4f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xec, 0x05, 0x99, 0x36,
	0x5a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlPlaneClient interface {
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	ListRuns(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
	ListAgents(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
}

type controlPlaneClient struct {
	cc *grpc.ClientConn
}

func NewControlPlaneClient(cc *grpc.ClientConn) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/adagio.rpc.controlplane.ControlPlane/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/adagio.rpc.controlplane.ControlPlane/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListRuns(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, "/adagio.rpc.controlplane.ControlPlane/ListRuns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, "/adagio.rpc.controlplane.ControlPlane/Inspect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListAgents(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, "/adagio.rpc.controlplane.ControlPlane/ListAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
type ControlPlaneServer interface {
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	ListRuns(context.Context, *ListRequest) (*ListRunsResponse, error)
	Inspect(context.Context, *InspectRequest) (*InspectResponse, error)
	ListAgents(context.Context, *ListRequest) (*ListAgentsResponse, error)
}

// UnimplementedControlPlaneServer can be embedded to have forward compatible implementations.
type UnimplementedControlPlaneServer struct {
}

func (*UnimplementedControlPlaneServer) Stats(ctx context.Context, req *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (*UnimplementedControlPlaneServer) Start(ctx context.Context, req *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedControlPlaneServer) ListRuns(ctx context.Context, req *ListRequest) (*ListRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRuns not implemented")
}
func (*UnimplementedControlPlaneServer) Inspect(ctx context.Context, req *InspectRequest) (*InspectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inspect not implemented")
}
func (*UnimplementedControlPlaneServer) ListAgents(ctx context.Context, req *ListRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}

func RegisterControlPlaneServer(s *grpc.Server, srv ControlPlaneServer) {
	s.RegisterService(&_ControlPlane_serviceDesc, srv)
}

func _ControlPlane_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adagio.rpc.controlplane.ControlPlane/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adagio.rpc.controlplane.ControlPlane/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adagio.rpc.controlplane.ControlPlane/ListRuns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListRuns(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adagio.rpc.controlplane.ControlPlane/Inspect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Inspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adagio.rpc.controlplane.ControlPlane/ListAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListAgents(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlPlane_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adagio.rpc.controlplane.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stats",
			Handler:    _ControlPlane_Stats_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _ControlPlane_Start_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _ControlPlane_ListRuns_Handler,
		},
		{
			MethodName: "Inspect",
			Handler:    _ControlPlane_Inspect_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _ControlPlane_ListAgents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/controlplane/service.proto",
}
