// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/adagio/adagio.proto

package adagio

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event_Type int32

const (
	Event_STATE_TRANSITION Event_Type = 0
)

var Event_Type_name = map[int32]string{
	0: "STATE_TRANSITION",
}

var Event_Type_value = map[string]int32{
	"STATE_TRANSITION": 0,
}

func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}

func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{1, 0}
}

type Node_State int32

const (
	Node_WAITING   Node_State = 0
	Node_READY     Node_State = 1
	Node_RUNNING   Node_State = 2
	Node_COMPLETED Node_State = 3
)

var Node_State_name = map[int32]string{
	0: "WAITING",
	1: "READY",
	2: "RUNNING",
	3: "COMPLETED",
}

var Node_State_value = map[string]int32{
	"WAITING":   0,
	"READY":     1,
	"RUNNING":   2,
	"COMPLETED": 3,
}

func (x Node_State) String() string {
	return proto.EnumName(Node_State_name, int32(x))
}

func (Node_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{3, 0}
}

type Run struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges                []*Edge  `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Run) Reset()         { *m = Run{} }
func (m *Run) String() string { return proto.CompactTextString(m) }
func (*Run) ProtoMessage()    {}
func (*Run) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{0}
}

func (m *Run) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Run.Unmarshal(m, b)
}
func (m *Run) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Run.Marshal(b, m, deterministic)
}
func (m *Run) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Run.Merge(m, src)
}
func (m *Run) XXX_Size() int {
	return xxx_messageInfo_Run.Size(m)
}
func (m *Run) XXX_DiscardUnknown() {
	xxx_messageInfo_Run.DiscardUnknown(m)
}

var xxx_messageInfo_Run proto.InternalMessageInfo

func (m *Run) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Run) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Run) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Run) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Event struct {
	Type                 Event_Type `protobuf:"varint,1,opt,name=type,proto3,enum=adagio.Event_Type" json:"type,omitempty"`
	RunID                string     `protobuf:"bytes,2,opt,name=runID,proto3" json:"runID,omitempty"`
	NodeName             string     `protobuf:"bytes,3,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() Event_Type {
	if m != nil {
		return m.Type
	}
	return Event_STATE_TRANSITION
}

func (m *Event) GetRunID() string {
	if m != nil {
		return m.RunID
	}
	return ""
}

func (m *Event) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

type GraphSpec struct {
	Nodes                []*Node_Spec `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges                []*Edge      `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GraphSpec) Reset()         { *m = GraphSpec{} }
func (m *GraphSpec) String() string { return proto.CompactTextString(m) }
func (*GraphSpec) ProtoMessage()    {}
func (*GraphSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{2}
}

func (m *GraphSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphSpec.Unmarshal(m, b)
}
func (m *GraphSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphSpec.Marshal(b, m, deterministic)
}
func (m *GraphSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphSpec.Merge(m, src)
}
func (m *GraphSpec) XXX_Size() int {
	return xxx_messageInfo_GraphSpec.Size(m)
}
func (m *GraphSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphSpec.DiscardUnknown(m)
}

var xxx_messageInfo_GraphSpec proto.InternalMessageInfo

func (m *GraphSpec) GetNodes() []*Node_Spec {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GraphSpec) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Node struct {
	Spec                 *Node_Spec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	State                Node_State `protobuf:"varint,2,opt,name=state,proto3,enum=adagio.Node_State" json:"state,omitempty"`
	StartedAt            string     `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt           string     `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{3}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetSpec() *Node_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Node) GetState() Node_State {
	if m != nil {
		return m.State
	}
	return Node_WAITING
}

func (m *Node) GetStartedAt() string {
	if m != nil {
		return m.StartedAt
	}
	return ""
}

func (m *Node) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

type Node_Spec struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Runtime              string   `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node_Spec) Reset()         { *m = Node_Spec{} }
func (m *Node_Spec) String() string { return proto.CompactTextString(m) }
func (*Node_Spec) ProtoMessage()    {}
func (*Node_Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{3, 0}
}

func (m *Node_Spec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node_Spec.Unmarshal(m, b)
}
func (m *Node_Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node_Spec.Marshal(b, m, deterministic)
}
func (m *Node_Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node_Spec.Merge(m, src)
}
func (m *Node_Spec) XXX_Size() int {
	return xxx_messageInfo_Node_Spec.Size(m)
}
func (m *Node_Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Node_Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Node_Spec proto.InternalMessageInfo

func (m *Node_Spec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node_Spec) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

type Edge struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eb97351c0f66fbe, []int{4}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Edge) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterEnum("adagio.Event_Type", Event_Type_name, Event_Type_value)
	proto.RegisterEnum("adagio.Node_State", Node_State_name, Node_State_value)
	proto.RegisterType((*Run)(nil), "adagio.Run")
	proto.RegisterType((*Event)(nil), "adagio.Event")
	proto.RegisterType((*GraphSpec)(nil), "adagio.GraphSpec")
	proto.RegisterType((*Node)(nil), "adagio.Node")
	proto.RegisterType((*Node_Spec)(nil), "adagio.Node.Spec")
	proto.RegisterType((*Edge)(nil), "adagio.Edge")
}

func init() { proto.RegisterFile("pkg/adagio/adagio.proto", fileDescriptor_5eb97351c0f66fbe) }

var fileDescriptor_5eb97351c0f66fbe = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x6b, 0xd4, 0x40,
	0x10, 0xef, 0xe5, 0xe3, 0x6a, 0xe6, 0xb4, 0xc4, 0x41, 0x34, 0x14, 0xc5, 0x23, 0x60, 0xbd, 0xa7,
	0x14, 0xaa, 0x6f, 0xbe, 0x18, 0xbd, 0x50, 0x02, 0x9a, 0x4a, 0x2e, 0xe2, 0xc7, 0x4b, 0xd9, 0x26,
	0x63, 0x2e, 0xc8, 0x65, 0x43, 0xb2, 0x11, 0x0a, 0x82, 0xef, 0xfe, 0xd5, 0xb2, 0x1f, 0xa9, 0x27,
	0xea, 0x53, 0xf2, 0xfb, 0xd8, 0xdd, 0xf9, 0xcd, 0x0c, 0x3c, 0xe8, 0xbe, 0xd6, 0xa7, 0xac, 0x62,
	0x75, 0xc3, 0xcd, 0x27, 0xea, 0x7a, 0x2e, 0x38, 0xce, 0x35, 0x0a, 0xbf, 0x83, 0x9d, 0x8f, 0x2d,
	0x1e, 0x81, 0xd5, 0x54, 0xc1, 0x6c, 0x39, 0x5b, 0x79, 0xb9, 0xd5, 0x54, 0xf8, 0x08, 0xa0, 0xec,
	0x89, 0x09, 0xaa, 0x2e, 0x99, 0x08, 0x2c, 0xc5, 0x7b, 0x86, 0x89, 0x05, 0x86, 0xe0, 0xb6, 0xbc,
	0xa2, 0x21, 0xb0, 0x97, 0xf6, 0x6a, 0x71, 0x76, 0x3b, 0x32, 0x77, 0x67, 0xbc, 0xa2, 0x5c, 0x4b,
	0xd2, 0x43, 0x55, 0x4d, 0x43, 0xe0, 0xfc, 0xe9, 0x49, 0xaa, 0x9a, 0x72, 0x2d, 0x85, 0x3f, 0xc0,
	0x4d, 0xbe, 0x51, 0x2b, 0xf0, 0x04, 0x1c, 0x71, 0xdd, 0x91, 0xaa, 0xe0, 0xe8, 0x0c, 0x6f, 0xbc,
	0x52, 0x8c, 0x8a, 0xeb, 0x8e, 0x72, 0xa5, 0xe3, 0x3d, 0x70, 0xfb, 0xb1, 0x4d, 0xd7, 0xa6, 0x24,
	0x0d, 0xf0, 0x18, 0x6e, 0xc9, 0x37, 0x33, 0xb6, 0xa3, 0xc0, 0x56, 0xc2, 0x0d, 0x0e, 0x1f, 0x82,
	0x53, 0xe8, 0x93, 0xfe, 0xa6, 0x88, 0x8b, 0xe4, 0xb2, 0xc8, 0xe3, 0x6c, 0x93, 0x16, 0xe9, 0x45,
	0xe6, 0x1f, 0x84, 0x1f, 0xc1, 0x3b, 0xef, 0x59, 0xb7, 0xdd, 0x74, 0x54, 0xe2, 0xd3, 0x29, 0xd5,
	0x4c, 0x55, 0x7c, 0x77, 0x3f, 0x55, 0x24, 0x1d, 0x7f, 0x45, 0xb3, 0xfe, 0x1f, 0xed, 0xa7, 0x05,
	0x8e, 0x3c, 0x88, 0x4f, 0xc0, 0x19, 0x3a, 0x2a, 0x55, 0xb4, 0x7f, 0x5e, 0xaa, 0x64, 0x5c, 0x81,
	0x3b, 0x08, 0x26, 0x48, 0x25, 0xdb, 0x6b, 0x81, 0xf6, 0x49, 0x25, 0xd7, 0x06, 0x39, 0x9b, 0x41,
	0xb0, 0xde, 0xcc, 0x46, 0xe7, 0xf5, 0x0c, 0x13, 0x0b, 0x7c, 0x0c, 0x8b, 0x2f, 0x4d, 0xdb, 0x0c,
	0x5b, 0xad, 0x3b, 0x4a, 0x87, 0x89, 0x8a, 0xc5, 0xf1, 0x73, 0x70, 0x54, 0x5c, 0x04, 0xa7, 0x95,
	0x1d, 0xd3, 0x53, 0x57, 0xff, 0x18, 0xc0, 0x61, 0x3f, 0xb6, 0xa2, 0xd9, 0x91, 0xe9, 0xf0, 0x04,
	0xc3, 0x17, 0xe0, 0xaa, 0x2a, 0x70, 0x01, 0x87, 0x1f, 0xe2, 0xb4, 0x48, 0xb3, 0x73, 0xff, 0x00,
	0x3d, 0x70, 0xf3, 0x24, 0x5e, 0x7f, 0xf2, 0x67, 0x92, 0xcf, 0xdf, 0x67, 0x99, 0xe4, 0x2d, 0xbc,
	0x03, 0xde, 0xeb, 0x8b, 0xb7, 0xef, 0xde, 0x24, 0x45, 0xb2, 0xf6, 0xed, 0xf0, 0x25, 0x38, 0xb2,
	0x37, 0x78, 0x1f, 0xe6, 0x03, 0x1f, 0xfb, 0x72, 0x7a, 0xd4, 0x20, 0x5c, 0xc2, 0xa2, 0xa2, 0x41,
	0x34, 0x2d, 0x13, 0x0d, 0x6f, 0xcd, 0xd3, 0xfb, 0xd4, 0xab, 0xd5, 0xe7, 0x93, 0xba, 0x11, 0xdb,
	0xf1, 0x2a, 0x2a, 0xf9, 0xee, 0xb4, 0x26, 0xde, 0xd7, 0xb4, 0x63, 0xe5, 0xb4, 0xdb, 0xbf, 0xd7,
	0xfc, 0x6a, 0xae, 0x16, 0xfc, 0xd9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x81, 0x8f, 0xb0,
	0xfb, 0x02, 0x00, 0x00,
}
