name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: make install
    - name: Start etcd
      run: docker-compose run -p 0.0.0.0:2379:2379 -d etcd
    - name: Run All Tests
      run: make test-with-integrations
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "github.ref == 'master'"
    needs: build
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: make docker-build
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: "adagiobot"
        password: ${{ secrets.ADAGIO_BOT_TOKEN }}
    - name: Push Images
      run: make docker-publish
