---
name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Build
      run: make docker-build
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: "adagiobot"
        password: ${{ secrets.ADAGIO_BOT_TOKEN }}
    - name: Push Images
      run: make docker-publish
